ktor:
    development: true
    application:
        modules:
            - com.blicket.ApplicationKt.module
    deployment:
        port: 8080
        watch:
            - classes
            - resources
        sslPort: 8443
    security:
      ssl:
          keyStore: keystore.jks
          keyAlias: sampleAlias
          keyStorePassword: password
          privateKeyPassword: password
